services:
  users-mngr:
    build:
      context: ./bbog-kata-users-mngr
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./bbog-kata-users-mngr:/app
      - /app/node_modules
    depends_on:
      - users-db

  users-web-ui:
    build:
      context: ./bbog-kata-users-web-ui
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=development
    volumes:
      - ./bbog-kata-users-web-ui:/app
      - /app/node_modules
    depends_on:
      - users-mngr

  users-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env.local
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
